replicaCount: 1

image:
  repository: infiniflow/ragflow
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8000
  
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ragflow.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""

config:
  logLevel: "info"
  embeddingModel: "BAAI/bge-small-en-v1.5"
  maxDocumentSize: 10485760  # 10MB
  
llm:
  provider: "openai"  # options: openai, azure, local
  model: "gpt-3.5-turbo"
  apiKey: ""  # Will be stored as a secret
  
milvus:
  enabled: true
  standalone:
    replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi

extraEnv: []
