apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ragflow.fullname" . }}-secrets
  labels:
    {{- include "ragflow.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.llm.apiKey }}
  LLM_API_KEY: {{ .Values.llm.apiKey | b64enc | quote }}
  {{- else }}
  LLM_API_KEY: ""
  {{- end }}
